const prompts = [
  ['The first thing', 'Before deciding whether anything is useful, name one detail you retained from the packet.'],
  ['The loose thread', 'Name one place where you wanted another sentence, source, or piece of context.'],
  ['The boundary', 'What did the packet carefully avoid claiming?'],
  ['The return visit', 'If you opened this again next week, what would you look for first?']
];
const deck = document.querySelector('#deck'); const form = document.querySelector('#record'); const preview = document.querySelector('#preview'); const exportButton = document.querySelector('#export'); let selected = null; let record = null;
const escape = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function select(index) { selected = index; [...deck.children].forEach((card, i) => card.classList.toggle('selected', i === index)); document.querySelector('#prompt-title').textContent = prompts[index][0]; document.querySelector('#prompt-copy').textContent = prompts[index][1]; }
prompts.forEach(([title, copy], index) => { const button = document.createElement('button'); button.type = 'button'; button.className = 'card'; button.innerHTML = `<span>0${index + 1}</span><strong>${title}</strong><small>${copy}</small>`; button.onclick = () => select(index); deck.append(button); });
function value(id) { return document.querySelector(`#${id}`).value.trim(); }
function list(label, text) { return `<article><h3>${label}</h3>${text ? `<p>${escape(text)}</p>` : '<p class="blank">Left blank — explicit blank.</p>'}</article>`; }
form.addEventListener('submit', event => { event.preventDefault(); if (selected === null) { document.querySelector('#status').textContent = 'Choose a prompt first.'; return; } record = { format: 'uncertainty-prompt-deck-reader-record/v1', boundary: 'Reader observations, misunderstandings, and unresolved questions only. No score, ranking, recommendation, or verdict.', prompt: { title: prompts[selected][0], text: prompts[selected][1] }, observations: value('observations'), misunderstandings: value('misunderstandings'), unresolvedQuestions: value('questions') }; preview.innerHTML = `<p class="eyebrow">Bounded reader record</p><h2>${escape(record.prompt.title)}</h2>${list('Retained observation', record.observations)}${list('Misunderstanding or friction', record.misunderstandings)}${list('Unresolved question', record.unresolvedQuestions)}<p class="boundary">${record.boundary}</p>`; exportButton.disabled = false; document.querySelector('#status').textContent = 'Preview ready.'; });
exportButton.onclick = () => { const blob = new Blob([JSON.stringify(record, null, 2)], { type: 'application/json' }); const link = Object.assign(document.createElement('a'), { href: URL.createObjectURL(blob), download: 'uncertainty-reader-record.json' }); link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 0); document.querySelector('#status').textContent = 'Export started.'; };
