const blocks = {
  garden: { label: 'Garden Battery', charge: 6, hazard: 'Floodwater', brief: 'The grid has failed. Three storm hours drain one charge per connected building. Available:', places: { maya: { name: "Maya's Flat", need: 'insulin stayed cold', kind: 'home' }, noah: { name: 'Noah & Jun', need: 'the nursery stayed warm', kind: 'home' }, hall: { name: 'Greenhouse Hall', need: 'eight neighbours had dry shelter', kind: 'refuge' }, reed: { name: 'Reed House', need: 'a radio stayed on', kind: 'home' }, shop: { name: "Alma's Shop", need: 'food stayed above floodwater', kind: 'home' } } },
  ridge: { label: 'Ridge Relay', charge: 7, hazard: 'Gale shear', brief: 'A midnight gale snaps every exposed east-line cable; choose which side of the hill can safely stay powered. Available:', places: { clinic: { name: 'Hill Clinic', need: 'vaccines stayed cold', kind: 'refuge' }, tower: { name: 'Signal Tower', need: 'the warning radio reached town', kind: 'home' }, rowan: { name: 'Rowan House', need: 'a wood stove stayed lit', kind: 'home' }, pier: { name: 'East Pump', need: 'the lower street stayed dry', kind: 'home', exposed: true }, sato: { name: 'Sato Home', need: 'an oxygen concentrator ran', kind: 'home', exposed: true } } },
  mill: { label: 'Mill Yard', charge: 11, hazard: 'Brackish seep', brief: 'Saltwater is pushing up through the old mill soil. A cable on a marked seep burns three extra charge keeping its connector dry. Available:', places: { bakery: { name: 'Night Bakery', need: 'the ovens held their proofing heat', kind: 'refuge' }, crane: { name: 'Crane House', need: 'a dialysis machine stayed running', kind: 'home' }, archive: { name: 'Town Archive', need: 'the emergency register stayed dry', kind: 'home' }, works: { name: 'Mill Works', need: 'the sump kept the workshop clear', kind: 'home', seep: true }, quay: { name: 'Quay Flat', need: 'an infant monitor stayed on', kind: 'home', seep: true } } }
};
let block = 'garden', selected = new Set(), ended = false;
const $ = s => document.querySelector(s);
const log = t => $('#log').insertAdjacentHTML('afterbegin', `<li>${t}</li>`);
const data = () => blocks[block];
function render() {
  const d = data();
  $('#blockName').textContent = d.label; $('#hazard').textContent = d.hazard; $('#briefText').textContent = d.brief; $('#charge').textContent = d.charge;
  $('#map').className = `map ${block}`;
  $('#places').innerHTML = Object.entries(d.places).map(([id, p]) => `<article class="place ${p.kind}${p.exposed ? ' exposed' : ''}${p.seep ? ' seep' : ''}" data-id="${id}"><small>${p.seep ? 'SALT SEEP · COSTLY' : p.exposed ? 'EAST LINE · EXPOSED' : p.kind === 'refuge' ? 'SHARED SPACE' : 'HOME'}</small><h2>${p.name}</h2><p>${p.need}</p><em>○</em></article>`).join('');
  $('#mapTitle').textContent = block === 'garden' ? 'Three cables. Five places.' : block === 'ridge' ? 'The east line will break at midnight.' : 'The ground itself is drinking the charge.';
  $('#mapCopy').textContent = block === 'garden' ? 'The greenhouse gives shelter, but every lit room makes the battery run lower.' : block === 'ridge' ? 'East-line homes are closer to the flooded street, but their cables will be cut. Keep them lit only if you can afford to lose the circuit.' : 'The mill’s salt seep does not cut a cable. It makes every connector laid there fight the ground all night. Spend charge on the yard only if its need is worth the whole block dimming.';
  document.querySelectorAll('.place[data-id]').forEach(el => el.onclick = () => toggle(el.dataset.id)); paint();
}
function paint() { document.querySelectorAll('.place[data-id]').forEach(e => e.classList.toggle('on', selected.has(e.dataset.id))); $('#slots').textContent = `${selected.size} / 3`; $('#powered').textContent = selected.size; }
function toggle(id) { if (ended) return; const p = data().places[id]; if (selected.has(id)) { selected.delete(id); log(`Cable pulled from ${p.name}.`); } else if (selected.size < 3) { selected.add(id); log(`Cable laid to ${p.name}.${p.seep ? ' The connector hisses in saltwater.' : ''}`); } else log('No cable slots left — pull one first.'); paint(); }
document.querySelectorAll('[data-block]').forEach(b => b.onclick = () => { if (ended) return; block = b.dataset.block; selected.clear(); $('#log').innerHTML = '<li>Rain ticks on the empty cables.</li>'; document.querySelectorAll('[data-block]').forEach(x => x.classList.toggle('chosen', x === b)); render(); });
$('#night').onclick = () => {
  if (ended) return; if (!selected.size) { log('Nobody is connected. The rain keeps falling.'); return; } ended = true;
  const d = data(), saved = [...selected]; let survivors, detail, remaining;
  if (block === 'garden') { remaining = d.charge - selected.size * 3; survivors = remaining >= 0 ? saved : saved.slice(0, 2); detail = remaining >= 0 ? 'Your battery carried every cable through all three storm hours.' : 'The battery died before dawn. The first two circuits held; the rest went dark.'; }
  else if (block === 'ridge') { const snapped = saved.filter(id => d.places[id].exposed); survivors = saved.filter(id => !d.places[id].exposed); remaining = d.charge - selected.size * 2; detail = snapped.length ? `Gale shear cut the east line at midnight: ${snapped.map(id => d.places[id].name).join(' and ')} went dark, even with charge left.` : 'You kept every cable west of the shear line. The gale found nothing exposed to cut.'; }
  else { const seeped = saved.filter(id => d.places[id].seep); remaining = d.charge - saved.length * 3 - seeped.length * 3; survivors = remaining >= 0 ? saved : saved.filter(id => !d.places[id].seep); detail = remaining >= 0 ? 'You kept the connectors dry enough. Every cable held against the brackish ground.' : `Brackish water drank the reserve: ${seeped.map(id => d.places[id].name).join(' and ')} pulled the whole yard down before dawn.`; }
  $('#charge').textContent = Math.max(0, remaining);
  document.querySelectorAll('.place[data-id]').forEach(el => { const held = survivors.includes(el.dataset.id), p = d.places[el.dataset.id]; el.classList.remove('on'); el.classList.add(held ? 'held' : 'flooded'); el.querySelector('p').textContent = held ? p.need : block === 'mill' && p.seep ? 'saltwater climbed the connector' : 'dark window · neighbours wait'; el.querySelector('em').textContent = held ? '✦' : '≈'; });
  $('#map').classList.add('aftermath'); $('#resultTitle').textContent = survivors.length >= 2 ? 'A hard, partial dawn.' : 'The storm took more than it should have.'; $('#resultText').textContent = detail;
  $('#resultList').innerHTML = Object.entries(d.places).map(([id, p]) => `<li>${survivors.includes(id) ? '✦' : '—'} <b>${p.name}</b>: ${survivors.includes(id) ? p.need : 'went dark'}</li>`).join(''); $('#result').showModal();
};
$('#restart').onclick = () => location.reload(); render();
