const blocks = [
  { id: 'garden', label: 'Garden Battery', hazard: 'Floodwater', brief: 'Floodwater is rising. Every connected building draws three reserve through the storm.', places: { maya: { name: "Maya's Flat", need: 'insulin stayed cold', kind: 'home' }, noah: { name: 'Noah & Jun', need: 'the nursery stayed warm', kind: 'home' }, hall: { name: 'Greenhouse Hall', need: 'eight neighbours had dry shelter', kind: 'refuge' }, reed: { name: 'Reed House', need: 'a radio stayed on', kind: 'home' }, shop: { name: "Alma's Shop", need: 'food stayed above floodwater', kind: 'home' } } },
  { id: 'ridge', label: 'Ridge Relay', hazard: 'Gale shear', brief: 'A midnight gale snaps every exposed east-line cable. West routes cost two reserve.', places: { clinic: { name: 'Hill Clinic', need: 'vaccines stayed cold', kind: 'refuge' }, tower: { name: 'Signal Tower', need: 'the warning radio reached town', kind: 'home' }, rowan: { name: 'Rowan House', need: 'a wood stove stayed lit', kind: 'home' }, pier: { name: 'East Pump', need: 'the lower street stayed dry', kind: 'home', exposed: true }, sato: { name: 'Sato Home', need: 'an oxygen concentrator ran', kind: 'home', exposed: true } } },
  { id: 'mill', label: 'Mill Yard', hazard: 'Brackish seep', brief: 'Saltwater pushes through the mill soil. A marked seep burns three extra reserve.', places: { bakery: { name: 'Night Bakery', need: 'the ovens held their proofing heat', kind: 'refuge' }, crane: { name: 'Crane House', need: 'a dialysis machine stayed running', kind: 'home' }, archive: { name: 'Town Archive', need: 'the emergency register stayed dry', kind: 'home' }, works: { name: 'Mill Works', need: 'the sump kept the workshop clear', kind: 'home', seep: true }, quay: { name: 'Quay Flat', need: 'an infant monitor stayed on', kind: 'home', seep: true } } }
];
let night = 0, reserve = 15, selected = new Set(), ended = false, history = [];
const $ = s => document.querySelector(s); const log = t => $('#log').insertAdjacentHTML('afterbegin', `<li>${t}</li>`); const data = () => blocks[night];
function render() {
  const d = data(); $('#blockName').textContent = `Night ${night + 1} · ${d.label}`; $('#hazard').textContent = d.hazard; $('#briefText').textContent = d.brief; $('#charge').textContent = reserve; $('#route').textContent = `${night} / 3 nights crossed`; $('#map').className = `map ${d.id}`;
  document.querySelectorAll('[data-block]').forEach((b, i) => { b.classList.toggle('chosen', i === night); b.classList.toggle('crossed', i < night); b.disabled = i !== night; });
  $('#places').innerHTML = Object.entries(d.places).map(([id, p]) => `<article class="place ${p.kind}${p.exposed ? ' exposed' : ''}${p.seep ? ' seep' : ''}" data-id="${id}"><small>${p.seep ? 'SALT SEEP · +3 COST' : p.exposed ? 'EAST LINE · WILL BREAK' : p.kind === 'refuge' ? 'SHARED SPACE' : 'HOME'}</small><h2>${p.name}</h2><p>${p.need}</p><em>○</em></article>`).join('');
  $('#mapTitle').textContent = night === 0 ? 'Spend carefully: the reserve has to last.' : night === 1 ? 'The routes behind you decide what remains.' : 'Last night. The route is the choice.';
  $('#mapCopy').textContent = night === 2 ? `You arrived with ${reserve} reserve. A normal cable costs three; seep cables cost six. You cannot protect everything now.` : 'The dawn receipt will carry forward: every generous cable tonight is a harder route tomorrow.';
  document.querySelectorAll('.place[data-id]').forEach(el => el.onclick = () => toggle(el.dataset.id)); paint();
}
function paint() { document.querySelectorAll('.place[data-id]').forEach(e => e.classList.toggle('on', selected.has(e.dataset.id))); $('#slots').textContent = `${selected.size} / 3`; $('#powered').textContent = selected.size; }
function toggle(id) { if (ended) return; const p = data().places[id]; if (selected.has(id)) { selected.delete(id); log(`Cable pulled from ${p.name}.`); } else if (selected.size < 3) { selected.add(id); log(`Cable laid to ${p.name}.${p.seep ? ' Salt hisses at the connector.' : ''}`); } else log('No cable slots left — pull one first.'); paint(); }
$('#night').onclick = () => {
  if (ended) return; if (!selected.size) { log('Nobody is connected. The rain keeps falling.'); return; } ended = true; const d = data(), saved = [...selected]; const seeped = saved.filter(id => d.places[id].seep); const exposed = saved.filter(id => d.places[id].exposed);
  const cost = night === 1 ? saved.length * 2 : saved.length * 3 + seeped.length * 3; reserve -= cost; let survivors = reserve >= 0 ? saved : []; let detail = `The route drew ${cost} reserve. ${Math.max(0, reserve)} remains for tomorrow.`;
  if (night === 1 && exposed.length) { survivors = survivors.filter(id => !d.places[id].exposed); detail = `Gale shear cut ${exposed.map(id => d.places[id].name).join(' and ')} at midnight. ${Math.max(0, reserve)} reserve crosses the ridge.`; }
  if (night === 2 && reserve < 0) detail = `The carried reserve was too thin. This route needed ${cost}; the storm took the last circuits before dawn.`;
  history.push({ label: d.label, cost, survivors: survivors.length, reserve: Math.max(0, reserve) }); reserve = Math.max(0, reserve);
  document.querySelectorAll('.place[data-id]').forEach(el => { const held = survivors.includes(el.dataset.id), p = d.places[el.dataset.id]; el.classList.remove('on'); el.classList.add(held ? 'held' : 'flooded'); el.querySelector('p').textContent = held ? p.need : 'dark window · neighbours wait'; el.querySelector('em').textContent = held ? '✦' : '≈'; });
  $('#map').classList.add('aftermath'); const final = night === 2; $('#resultTitle').textContent = final ? (survivors.length >= 2 ? 'The route held until dawn.' : 'A thin, costly dawn.') : 'Dawn carries forward.'; $('#resultText').textContent = detail; $('#resultList').innerHTML = history.map(h => `<li><b>${h.label}</b> — ${h.survivors} held · spent ${h.cost} · carried ${h.reserve}</li>`).join(''); $('#continue').textContent = final ? 'Start a new three-night route' : 'Carry the dawn forward →'; $('#result').showModal();
};
$('#continue').onclick = () => { $('#result').close(); if (night === 2) location.reload(); else { night++; selected.clear(); ended = false; $('#log').innerHTML = '<li>The next storm is already moving in.</li>'; render(); } };
render();
