const intervals=[
 {title:'The seed pump is coughing.',brief:'A crate of seedlings will spoil unless the pump gets power. The clock will clear this room in one minute.',actions:[['Tag the blue valve','CLUE · the safe valve is blue',0,'blue','You tie blue thread to the valve wheel.'],['Run the pump blind','CHARGE −1 · no clue',-1,null,'The pump starts, but the room gives you nothing back.']]},
 {title:'You wake to a dark sluice.',brief:'The pump has stopped. A small card from somebody with your handwriting is all that crossed the interval.',actions:[['Open the blue valve','requires blue clue · CHARGE +1',1,null,'The blue valve opens cleanly. Water returns to the seed beds.'],['Pry the red valve','CHARGE −1 · damages the line',-1,'red','The red valve gives with a crack. You write down the sound, not the cost.']]},
 {title:'The delivery bell is already ringing.',brief:'The seedlings need a final route before daylight. You have what earlier wake-ups deliberately left.',actions:[['Send the cart by the blue route','requires blue clue · finish with charge 3+',0,null,'The blue thread leads the cart around the flooded culvert. The seedlings arrive warm.'],['Send it by the red route','requires red clue · CHARGE −1',-1,null,'The cart takes the broken line. It arrives, but the last battery goes with it.']]}
];
let state; const $=x=>document.getElementById(x); const has=x=>state.clues.includes(x);
function start(){state={i:0,charge:3,clues:[],history:[]};render()}
function render(){ $('shift').textContent=state.i<3?`INTERVAL 0${state.i+1}`:'DAWN'; $('charge').textContent=`CHARGE ${state.charge}`;$('clue-count').textContent=`CLUES ${state.clues.length}`;if(state.i===3)return ending();let s=intervals[state.i];let cards=s.actions.map((a,n)=>`<button data-a="${n}"><strong>${a[0]}</strong><small>${a[1]}</small></button>`).join('');$('game').innerHTML=`<p class="stamp">WAKE-UP ${String(state.i+1).padStart(2,'0')} / CLOCK MEMORY: EMPTY</p><h2>${s.title}</h2><p>${s.brief}</p><aside><b>WHAT CROSSED THE LAST CLOCK</b>${state.clues.length?`<ul>${state.clues.map(c=>`<li>${c==='blue'?'Blue valve: safe water route':'Red valve: damaged line'}</li>`).join('')}</ul>`:'<p>Nothing marked. Nothing certain.</p>'}</aside><div class="actions">${cards}</div>`;document.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>choose(s.actions[b.dataset.a]))}
function choose(a){let requires=a[1].match(/requires (blue|red)/);if(requires&&!has(requires[1])){$('game').insertAdjacentHTML('beforeend',`<div class="result bad">THE CLOCK LEFT NO ${requires[1].toUpperCase()} CLUE. You can still choose, but not this route.</div>`);return}state.charge+=a[2];if(a[3])state.clues.push(a[3]);state.history.push([a[0],a[3]||requires?.[1]||'none']);$('game').insertAdjacentHTML('beforeend',`<div class="result"><b>MARKED BEFORE THE BELL.</b><br>${a[4]}${a[3]?`<p>CLUE SEALED: ${a[3].toUpperCase()}</p>`:''}<button id="next">Let the clock clear →</button></div>`);document.querySelectorAll('[data-a]').forEach(b=>b.disabled=true);$('next').onclick=()=>{state.i++;render()}}
function ending(){let win=has('blue')&&state.charge>=3; $('game').innerHTML=`<div class="ending ${win?'':'bad'}"><p class="stamp">DAWN RECEIPT</p><h2>${win?'The cart finds the dry road.':'The clock leaves a cost.'}</h2><p>${win?'A blue thread, marked by a self you cannot remember, gets the seedlings past the culvert.':'The route is missing a clue or the battery is gone. The seedlings arrive late, and you can name why.'}</p><aside><b>WHAT CARRIED YOU</b><ul>${state.history.map((h,i)=>`<li>INTERVAL 0${i+1}: ${h[0]} — ${h[1]}</li>`).join('')}</ul></aside><button id="again">Run it again →</button></div>`;$('again').onclick=start}
$('reset').onclick=start;start();