const cards=[
  {name:'Sunspill Garden',tag:'A small browser game',stamp:'Postcard 01 / kept 17 Sep 2026',lines:[['The maker saved this version','9b4a7e1'],['Someone played it in a browser','A screenshot was kept on 17 Sep 2026'],['A public address was reached','example.test/sunspill']],facts:['The saved version is identified as 9b4a7e1.','A browser playthrough and public address were observed on 17 Sep 2026.'],gaps:['Nothing here says the address works today.','Nothing here says the source still points to that saved version.']},
  {name:'Archive Lantern',tag:'A keyboard-only web toy',stamp:'Postcard 02 / kept 16 Sep 2026',lines:[['The maker changed the saved version','c8d03f2 (was 51af920)'],['Someone had played an earlier version','A keyboard-flow screenshot was kept on 16 Sep 2026'],['An address was once written down','example.test/archive-lantern']],facts:['The saved version changed from 51af920 to c8d03f2.','A keyboard-flow screenshot and public address were retained from 16 Sep 2026.'],gaps:['No playthrough was kept for c8d03f2.','No one recorded whether the address worked after the change.']}
];
let at=0;const notes=[];const esc=s=>s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
function cardView(card){return `<section class="postcard"><div class="postcard-head"><p>${card.stamp}</p><h2>${card.name}</h2><em>${card.tag}</em></div><dl>${card.lines.map(([a,b])=>`<div><dt>${a}</dt><dd>${b}</dd></div>`).join('')}</dl></section>`}
function form(card){return `<form id="notes"><p class="step">YOUR FIRST LOOK / ${at+1} OF ${cards.length}</p><label>What can you say about ${card.name} from this postcard?<textarea name="establishes" required maxlength="800" placeholder="Only what this postcard gives you…"></textarea></label><label>What is still unsettled?<textarea name="uncertain" required maxlength="800" placeholder="What would you not assume yet?"></textarea></label><label>What would you ask or check next?<textarea name="question" required maxlength="800" placeholder="One useful next question…"></textarea></label><button>${at===cards.length-1?'Set these notes aside':'Read the next postcard'} <span>→</span></button></form>`}
function review(){const comparison=cards.map((c,i)=>`<article><p class="step">POSTCARD ${String(i+1).padStart(2,'0')} / COMPARISON</p><h2>${c.name}</h2><div class="columns"><section><h3>What the postcard retained</h3><ul>${c.facts.map(x=>`<li>${x}</li>`).join('')}</ul></section><section class="gaps"><h3>What it did not settle</h3><ul>${c.gaps.map(x=>`<li>${x}</li>`).join('')}</ul></section></div><details><summary>My first-look notes</summary><p><b>I could say:</b> ${esc(notes[i].establishes)}</p><p><b>I left unsettled:</b> ${esc(notes[i].uncertain)}</p><p><b>I would ask:</b> ${esc(notes[i].question)}</p></details></article>`).join('');return `<section class="review"><p class="kicker">AFTER BOTH FIRST LOOKS</p><h1>Put your notes beside what was retained.</h1><p>This is a comparison, not a correction. It records what each postcard carried forward and what it did not establish.</p>${comparison}<button id="download">Download my notes <span>↓</span></button><output id="notice" aria-live="polite"></output></section>`}
function render(){document.querySelector('#stage').innerHTML=at<cards.length?cardView(cards[at])+form(cards[at]):review();if(at<cards.length)document.querySelector('#notes').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.currentTarget);notes.push(Object.fromEntries(d));at++;render()});else document.querySelector('#download').addEventListener('click',download)}
function download(){const payload={kind:'blind-provenance-postcard-reading-packet',boundary:'First-look reader notes beside retained facts and explicit gaps; no grade, ranking, or freshness verdict.',read_at:new Date().toISOString(),responses:cards.map((card,i)=>({postcard:card.name,...notes[i]}))};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));a.download='first-look-postcard-notes.json';a.click();URL.revokeObjectURL(a.href);document.querySelector('#notice').textContent='Downloaded locally. No notes were sent anywhere.'}
render();
