const shifts = [
  { title: 'Rain is climbing the relay wall.', brief: 'You wake to wet glass, a sagging battery, and a note in somebody else’s handwriting: “The garden hates sudden dark.” The bell will ring before you can do everything.', actions: [
    {name:'Patch the relay', detail:'GRID +2 · no note survives', grid:2, trust:-1, memory:null, result:'You keep the lamps on. You are certain this was the right repair, but cannot say what the garden needed.'},
    {name:'Seal a hurried gate note', detail:'NOTE: “close west gate” · GRID +1', grid:1, trust:0, memory:'Close the west gate before rain.', result:'You write quickly: “close west gate before rain.” It sounds decisive. You do not say what the gate is protecting.'},
    {name:'Leave a weather note', detail:'NOTE: rain pattern · GRID +1', grid:1, trust:0, memory:'Rain climbs the west relay after midnight; dim the lamps first.', result:'You name both the rain and the lamp. It is a little longer, but the next operator will know where to begin.'},
    {name:'Wake the glass moths', detail:'TRUST +2 · GRID −1', grid:-1, trust:2, memory:'Glass moths settle when the blue lamp is low.', result:'The moths orbit the blue lamp. They remember your hands, which is not the same as remembering you.'}
  ]},
  { title: 'The bell erased the feeling, not the damage.', brief: 'You wake halfway through a wind alarm. The room is familiar in the way a dream is familiar. What did the earlier operator mean by these scraps?', actions: [
    {name:'Follow the weather note', detail:'requires weather note · GRID +2 · TRUST +2 · NOTE', require:'weather', grid:2, trust:2, memory:'West drain clear; relay route marked in blue.', result:'The careful wording sends you to the low lamp first. A drain crew finds the marked route before the water can reach the relay. You seal their relay route for the third wake-up.'},
    {name:'Release the jammed west gate', detail:'requires hurried gate note · GRID +1 · TRUST +2', require:'gate', grid:1, trust:2, memory:null, result:'The sealed order did exactly what it said: it shut the gate on a flooded walkway. You release the latch, wade through the spill, and get the neighbours out.'},
    {name:'Follow the surviving note', detail:'requires a note · GRID +2 · TRUST +1', require:true, grid:2, trust:1, memory:'Blue lamp low. West relay holds through rain.', result:'The old handwriting gets you through the wind. You do not remember writing it, but it has your caution in it.'},
    {name:'Drain the pond', detail:'GRID +1 · TRUST −2', grid:1, trust:-2, memory:null, result:'The alarm quiets. The garden goes still in a way that feels like a warning.'},
    {name:'Listen at the seed vault', detail:'TRUST +2 · NOTE: seed timing', grid:0, trust:2, memory:'Seeds open after the second bell, never before.', result:'A seed clicks beneath the vault door. You write down the time before the bell can take it.'}
  ]},
  { title: 'Third bell. One chance to leave a morning.', brief: 'Dawn is pressing against the shutters. The machine needs power, and the garden needs someone to have noticed it. You have minutes, not a continuous self.', actions: [
    {name:'Route power by the notes', detail:'requires 2 notes · GRID +2 · TRUST +1', require:2, grid:2, trust:1, memory:null, result:'The scraps make a map. You route power as if the earlier shifts are standing beside you.'},
    {name:'Open the dawn route', detail:'requires hurried gate note · GRID +2 · TRUST +1', require:'gate', grid:2, trust:1, memory:null, result:'Because you remember which gate was wrongly closed, you keep the dawn crew out of the same flood. The mistake becomes a route through it.'},
    {name:'Force the emergency cycle', detail:'GRID +2 · TRUST −2', grid:2, trust:-2, memory:null, result:'The machine obeys. Outside, petals close against the sudden current.'},
    {name:'Keep the blue lamp low', detail:'requires a moth note · TRUST +3 · GRID +4', require:'moth', grid:4, trust:3, memory:null, result:'Moths settle on the relay casing. Their tiny weight steadies the current long enough to matter. The garden’s own current carries dawn through the relay.'}
  ]}
];
let state;
const $ = (id) => document.getElementById(id);
function start() { state={shift:0,grid:3,trust:3,notes:[],actions:[],picked:false}; render(); }
function memories() { return state.notes.length ? `<ul>${state.notes.map(n=>`<li>${n}</li>`).join('')}</ul>` : '<p class="empty">Nothing was deliberately preserved. The last shift is gone.</p>'; }
function noteKind() { const notes=state.notes.join(' '); return notes.includes('Close the west gate') ? 'gate' : notes.includes('Rain climbs the west relay') ? 'weather' : ''; }
function consequence() { if (state.shift !== 1) return ''; const kind=noteKind(); if(kind==='gate') return '<aside class="consequence danger"><b>VISIBLE CONSEQUENCE — WEST WALKWAY FLOODED</b><p>The night crew followed your sealed words exactly and closed the west gate. Water has nowhere to go; a yellow lamp flashes beyond the locked latch.</p></aside>'; if(kind==='weather') return '<aside class="consequence rescue"><b>VISIBLE CONSEQUENCE — WEST DRAIN CREW ARRIVED</b><p>Your note named the rain and the lamp. Blue-coated neighbours have found the drain before the relay wall floods.</p></aside>'; return ''; }
function render() {
  $('grid').textContent=state.grid+'/7'; $('trust').textContent=state.trust+'/7'; $('notes-count').textContent=state.notes.length; $('shift-stamp').textContent=state.shift < 3 ? `SHIFT 0${state.shift+1} / 03` : 'DAWN REPORT';
  if (state.shift === 3) return ending();
  const s=shifts[state.shift]; const orientation=state.shift===0?`<aside class="operator-card"><b>OPERATOR'S CARD / READ BEFORE THE BELL</b><p>Choose one response tonight. A choice marked <strong>NOTE</strong> becomes a scrap the next wake-up can use; the bell takes everything else.</p><div><span>DAWN TARGET</span><strong>GRID 6+ · GARDEN TRUST 6+</strong></div></aside><aside class="note-compare"><b>SEALED-WORDING CHECK / TWO RECOVERABLE RISKS</b><div><p><strong>“Close west gate”</strong><br>Fast and narrow: it may protect the relay while trapping water at the walkway. A later operator can release it.</p><p><strong>Rain + blue lamp</strong><br>Specific and shared: it can bring the drain crew to the relay. Their marked route can become a new note.</p></div></aside>`:''; const buttons=s.actions.map((a,i)=>`<button class="action ${a.memory?'keeps-note':''}" data-action="${i}" ${state.picked?'disabled':''}><strong>${a.name}</strong><small>${a.detail}</small></button>`).join('');
  $('game').innerHTML=`<p class="shift-label">WAKE-UP ${String(state.shift+1).padStart(2,'0')} · MEMORY BUFFER: EMPTY</p><h2>${s.title}</h2><p class="brief">${s.brief}</p>${orientation}${consequence()}<aside class="memory-board"><b>WHAT MADE IT ACROSS THE BELL</b>${memories()}</aside><div class="actions">${buttons}</div>`;
  document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>choose(s.actions[Number(b.dataset.action)])));
}
function choose(a) {
  const hasMoth=state.notes.some(n=>n.includes('Glass moths'));
  const kind=noteKind();
  const enough=typeof a.require==='number' ? state.notes.length>=a.require : a.require==='moth' ? hasMoth : a.require==='gate' ? kind==='gate' : a.require==='weather' ? kind==='weather' : !a.require || state.notes.length>0;
  if (!enough) { const needed=a.require==='moth'?'the moth note':a.require==='gate'?'the hurried gate note':a.require==='weather'?'the careful weather note':a.require+' preserved notes'; $('game').insertAdjacentHTML('beforeend', `<div class="result"><b class="lost">YOU REACH FOR A MEMORY THAT ISN’T THERE.</b><br>This action needs ${needed}. Choose what this shift can actually know.</div>`); return; }
  state.picked=true; state.grid+=a.grid; state.trust+=a.trust; state.actions.push({name:a.name, kept:a.memory, used:a.require || false}); if(a.memory) state.notes.push(a.memory); $('grid').textContent=state.grid+'/7'; $('trust').textContent=state.trust+'/7'; $('notes-count').textContent=state.notes.length;
  $('game').insertAdjacentHTML('beforeend', `<div class="result"><b>SHIFT LOGGED.</b><br>${a.result}${a.memory?`<p class="sealed">NOTE SEALED FOR THE NEXT WAKE-UP: ${a.memory}</p>`:''}<button class="continue" type="button">Let the bell ring →</button></div>`); document.querySelector('.continue').addEventListener('click',()=>{state.shift++;state.picked=false;render();}); document.querySelectorAll('[data-action]').forEach(b=>b.disabled=true);
}
function ending() { const good=state.grid>=6 && state.trust>=6; const partial=state.grid>=5 || state.trust>=5; const title=good?'Morning knows where to land.':partial?'The garden survives, but does not forgive.':'The machine wakes alone.'; const body=good?'Your notes became a bridge between people who were all you. Lamps come up slowly; moths settle; the garden opens on purpose.':partial?'You preserved one half of the night. At dawn there is power or there are flowers, but not the small agreement that would have held both.':'The last shift solved nothing it could carry. The relay is bright, the garden is dark, and every good intention vanished with the bell.'; const record=state.actions.map((a,i)=>`<li>SHIFT 0${i+1}: ${a.name} <span>${a.used==='gate'?'↳ acted on the hurried gate note':a.used==='weather'?'↳ acted on the careful weather note':a.used?'↳ used preserved notes':a.kept?'↳ kept as a note':'↳ the reason disappeared with the bell'}</span></li>`).join(''); $('game').innerHTML=`<div class="ending ${good?'':'failure'}"><p class="shift-label">DAWN / FINAL STATE: GRID ${state.grid}, TRUST ${state.trust}, NOTES ${state.notes.length}</p><h2>${title}</h2><p>${body}</p><aside class="memory-board"><b>NIGHT RECEIPT — WHAT YOU DID / WHAT SURVIVED</b><ul>${record}</ul></aside><button class="continue" type="button" id="again">Run another night →</button></div>`; $('again').addEventListener('click',start); }
$('reset').addEventListener('click',start); start();
